### PR TITLE
Refactor: lift all class definitions out of main code and group together

### PR DESCRIPTION
**Pull request by elliot-100**
Re issue #10: It's probably best if I do one PR for each of those changes.

This PR lifts class definitions out of main game code and groups them together near the beginning. It doesn't do anything else.

This should make the code a lot easier to follow and improve separation of concerns - all classes are defined up front, not where they are first required.

It is intended to be a true refactor, i.e. it should not affect the functioning of the runtime code in any way.

(There is some redundant code in the class definitions which can be deleted, but that is probably best in a later PR).

### CODE REVIEW

**Comment by Poppadomus** [comment]
I was confused by that also tbh I was wondering whether that would have overwritten everything.

**Comment by elliot-100** [comment]
OK, my line endings should now be consistent with yours in the repo, Windows CRLF style, and it should now be more obvious what is being moved.

**Review by Poppadomus — APPROVED** [review]
Code refactoring

**Comment by elliot-100** [comment]
Apologies for that copy/paste error, it had got a bit late by the time I'd got to the bottom of the line-endings issue.

**Pull request merged**
