### PR TITLE
Refactor: extract `HealthBar` class

### PR DESCRIPTION
**Pull request by elliot-100**
Re #32, this PR extracts repeated code to a `HealthBar` class which can be called by any entity that has `health` and `max-health` attributes.

To support this I have added the `Player.max_health` attribute.

The PR is raised against your 'Dev/Test-build' branch.

Is that the idea? If so could you set it as default please, and try not to rename it again, as that does impact contributors' forks? Thank you.

### CODE REVIEW

**Comment by Poppadomus** [comment]
Hi I hadn't really planned to use that yet I'm just trying to understand the work flow.

**Comment by elliot-100** [comment]
You did ask me to do it here: https://github.com/Poppadomus/pygameTDS/issues/32, though.

Then closed as completed...

**Comment by Poppadomus** [comment]
My bad we can probably just go ahead and push this to stable branch, there would have to be something to ensure that players health bar is always visible and zombies healthbar is only visible if damaged I think that's why I used 2 seperate health bars.

Perhaps zombie health bar should hide again once it hasn't took damage for a few seconds could help on performance displaying lots of healthbars can't be great for performance.

**Comment by elliot-100** [comment]
> My bad we can probably just go ahead and push this to stable branch

I don't understand what you are saying here. I raised against [Poppadomus:Dev/Test-build](https://github.com/Poppadomus/pygameTDS/tree/Dev/Test-build) and that's where I checked that behaviour was same as before: Player's healthbar is always visible and Zombie's healthbar is only visible if damaged.

> Perhaps zombie health bar should hide again once it hasn't took damage for a few seconds could help on performance displaying lots of healthbars can't be great for performance.

That is a possible enhancement, this is intended to be a true refactor (changed implementation, unchanged behaviour).

**Pull request merged**
