### PR TITLE
Fix: zombie image load for reduced set of images

### PR DESCRIPTION
**Pull request by elliot-100**
Fixes issue #12

### CODE REVIEW

**Comment by Poppadomus** [comment]
Hi i have fixed it already forgot to update the number for images

**Review by Poppadomus — COMMENTED** [review]
Hey, thanks for the help with that relatively quick fix, i've added a wiki section to help with the code maintainability with all of the pygame funcs described.

**Comment by elliot-100** [comment]
That info should be in the code as docstrings.

**Comment by elliot-100** [comment]
And the fix is not in the code.

**Pull request closed without merging**
