### PR TITLE
Refactor: reorder code for clarity

### PR DESCRIPTION
**Pull request by elliot-100**
This PR reorders`Game.py` so that all constants are declared first, then all classes, then all module functions.

It should make it easier to follow and make changes in future.

(Constants and classes should probably be split out into separate files, but I don't think that's feasible right now, as there are issues with game state which need to be resolved first - for example, I don't think all of those constants are really constant).

It also puts two blank lines between definitions as per PEP8 recommendation.

### CODE REVIEW

**Comment by Poppadomus** [comment]
Sorry if the code is a bit confusing you are welcome to tidy it up a bit if you would like I've been adding and removing snippets for some stuff over time and it hasn't had a tidy up in a while also, I am aware that some of the constants don't work I hadn't fully tested a lot of the implementation for the constants that don't work though they will usually be defined somewhere else possibly even in the main loop.

**Review by Poppadomus — APPROVED** [review]
Sure, you can make these changes although it would save me some time and effort

**Comment by elliot-100** [comment]
I'm happy to help a bit, as this project helps me put some of my recent Pygame/pathfinding learning into practice. I'm pretty sure you've followed the same Red Blob Games tutorials on A-star!

I can look at constants next.

You will need to merge the PR - I would recommend 'merge commit' rather than other options as this keeps a history of individual commits, as well as an overall one which is useful to e.g. auto-populate release notes.

**Comment by Poppadomus** [comment]
> I'm happy to help a bit, as this project helps me put some of my recent Pygame/pathfinding learning into practice. I'm pretty sure you've followed the same Red Blob Games tutorials on A-star!
> 
> I can look at constants next.
> 
> You will need to merge the PR - I would recommend 'merge commit' rather than other options as this keeps a history of individual commits, as well as an overall one which is useful to e.g. auto-populate release notes.

Check last update i did it refactored a lot of it already

**Comment by elliot-100** [comment]
Generally it would be good practice to not just close a PR like this - GitHub allows contributors to revise their PR on top of incoming changes, by rebasing.

**Pull request closed without merging**
